# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 288f987579ecf8bc15d851fa568468f597d035e7080244c98b4136062f6c19e3f3f5488044012f0e46555e9ab30542924e2bf6388af4cb662c7fdf211bfa03cd

test:
  secret_key_base: 2489d08427534a7f7fae14fb92e38ab7f3206d99314d722a76b4208ce6acf3538d86c7f8871995da6db8e88993eb02215987bdcbff9e5ca53b5dba3e715ebbbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
